### PR TITLE
WIP: [FEAT]: Typescript

### PR DESCRIPTION
**Pull request by NullVoxPopuli**
@runspired : 
 - idk how much conversion you want right away, but converting is pretty easy. :)
 - also, would you want this PR to have a passing build before merging?

Current configuration:
 - allow JS
 - fail the build if there are any type errors.
 - _strict_

### CODE REVIEW

**Comment by runspired** [comment]
@NullVoxPopuli thanks! Yes, we should get this green before merging.

In terms of how much conversion, it would be nice to get to a point where we either don't have any `any` usage or *nearly* don't. I think @mnorth is much more of a typescript wizard than I am in this area and there are some places such as `target` where `target` can change quite a bit (could be `document`, `resource`, `resource-identifier` `relationships` hash `relationship object`, `attributes` hash, `jsonapi` `meta` `links` etc.).

#2 should resolve most of the linting issues once that lands (I suspect having it land first would be best since getting us to green should make future PRs nicer)

**Comment by NullVoxPopuli** [comment]
Cool, I'll wait on #2 before getting this green :)

**Comment by NullVoxPopuli** [comment]
Oh, also, I can get rid of all the any usage. :) I was just being lazy / uncertain in a few places. :)

**Comment by runspired** [comment]
@NullVoxPopuli #2 is merged

**Comment by NullVoxPopuli** [comment]
aaaand now I'm apparently bad importing things :(

**Comment by NullVoxPopuli** [comment]
something weird between master and this branch -- I think only half as many tests run? 
96 tests, 23 skipped -  111 assertions
vs the 46 tests, 23 skipped - 61 assertions
in here. 

Other things I noticed, and would like to address in a future PR:
 - constructor signatures for related classes vary quite a bit
 - validation error classes could maybe have `buildMetaErrorMessage` as a private member?
 - use typescript enums in place of `number` for the `*_TYPES`

**Comment by NullVoxPopuli** [comment]
with linting disabled:
ts:
```
37 tests completed in 654 milliseconds, with 0 failed, 23 skipped, and 0 todo.
52 assertions of 52 passed, 0 failed.
```

master:
```
37 tests completed in 630 milliseconds, with 0 failed, 23 skipped, and 0 todo.
52 assertions of 52 passed, 0 failed.
```

**Pull request merged**
