### PR TITLE
Fix validator chain.

### PR DESCRIPTION
**Pull request by arjunkathuria**
Tries to fix the `schemaFor` not defined error by passing down the `validator` object down and accessing its schemaFor prop.

does this seem to be the correct direction to proceed ?

### CODE REVIEW

**Comment by arjunkathuria** [comment]
@runspired Sweet, so make contexts objects with the existing arguments of functions and pass it as the only argument that is going to be destructured, we'd have to do this for multiple functions if i understand correctly ?

**Comment by runspired** [comment]
@arjunkathuria yes, see `validate-document` and the methods it calls to understand. There's a standard object. `typescript` would make this more clear but I haven't had time to convert. @nullvoxpopuli might find that a nice way to contribute here :)

**Comment by NullVoxPopuli** [comment]
yeah, I'll give it a go. woo woo typescript :)

**Comment by runspired** [comment]
@arjunkathuria I think you need to rebase

**Comment by runspired** [comment]
looks like the failures are just the non-implemented tests :D

**Comment by runspired** [comment]
@arjunkathuria want to skip the not implemented tests for now?

**Comment by arjunkathuria** [comment]
@runspired i don't really know what they mean anyway and its 1AM here already so, sure.

**Pull request merged**
